// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Professionals.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Professionals.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProfessionalsDbContext))]
    [Migration("20251223151914_ReplaceStartEndPriceWithVisitPrice")]
    partial class ReplaceStartEndPriceWithVisitPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("professionals")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_days");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_availability_days_professional_id");

                    b.ToTable("availability_days", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvailabilityDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_day_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_slots");

                    b.HasIndex("AvailabilityDayId")
                        .HasDatabaseName("ix_availability_slots_availability_day_id");

                    b.ToTable("availability_slots", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearReceived")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("year_received");

                    b.HasKey("Id")
                        .HasName("pk_awards");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_awards_professional_id");

                    b.ToTable("awards", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degree");

                    b.Property<string>("EndYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("end_year");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_of_study");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("boolean")
                        .HasColumnName("is_currently_studying");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("start_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_educations");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_educations_professional_id");

                    b.ToTable("educations", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.PrimitiveCollection<List<string>>("Services")
                        .HasColumnType("text[]")
                        .HasColumnName("services");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<int?>("VisitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("visit_price");

                    b.HasKey("Id")
                        .HasName("pk_professionals");

                    b.ToTable("professionals", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.VerificationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_url");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_verification_documents");

                    b.HasIndex("ProfessionalId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_documents_professional_id_type");

                    b.ToTable("verification_documents", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("EndYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("end_year");

                    b.Property<bool>("IsCurrentPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_position");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("organization");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("start_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_experiences");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_work_experiences_professional_id");

                    b.ToTable("work_experiences", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("AvailabilityDays")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_days_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.AvailabilityDay", "Day")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("AvailabilityDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_slots_availability_days_availability_day_id");

                    b.OwnsOne("Modules.Common.Features.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("AvailabilitySlotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.HasKey("AvailabilitySlotId");

                            b1.ToTable("availability_slots", "professionals");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilitySlotId")
                                .HasConstraintName("fk_availability_slots_availability_slots_id");
                        });

                    b.Navigation("Day");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Award", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("Awards")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_awards_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Education", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("Educations")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educations_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.VerificationDocument", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("VerificationDocuments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_documents_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_experiences_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Navigation("AvailabilityDays");

                    b.Navigation("Awards");

                    b.Navigation("Educations");

                    b.Navigation("VerificationDocuments");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
