// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Professionals.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Professionals.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProfessionalsDbContext))]
    [Migration("20260316072155_RefactorServicesLookupTable")]
    partial class RefactorServicesLookupTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("professionals")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_days");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_availability_days_professional_id");

                    b.ToTable("availability_days", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvailabilityDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_day_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_slots");

                    b.HasIndex("AvailabilityDayId")
                        .HasDatabaseName("ix_availability_slots_availability_day_id");

                    b.ToTable("availability_slots", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearReceived")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("year_received");

                    b.HasKey("Id")
                        .HasName("pk_awards");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_awards_professional_id");

                    b.ToTable("awards", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degree");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("EndYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("end_year");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_of_study");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("boolean")
                        .HasColumnName("is_currently_studying");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("start_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_educations");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_educations_professional_id");

                    b.ToTable("educations", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<int>("VisitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("visit_price");

                    b.HasKey("Id")
                        .HasName("pk_professionals");

                    b.ToTable("professionals", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_services_name");

                    b.ToTable("services", "professionals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Name = "Consultation Initiale"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Name = "Visite de Suivi"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Name = "Téléconsultation"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Name = "Consultation d'Urgence"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000005"),
                            Name = "Deuxième Avis"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000006"),
                            Name = "Renouvellement d'Ordonnance"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000007"),
                            Name = "Certificat Médical"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000008"),
                            Name = "Bilan de Santé"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000009"),
                            Name = "Vaccination"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000010"),
                            Name = "Procédure Mineure"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000011"),
                            Name = "Soins des Plaies"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000012"),
                            Name = "Médecine des Voyages"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000013"),
                            Name = "Visite de l'Enfant Sain"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000014"),
                            Name = "Gestion des Maladies Chroniques"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000015"),
                            Name = "Soins Préventifs"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000016"),
                            Name = "Consultation Diagnostique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000017"),
                            Name = "Évaluation Préopératoire"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000018"),
                            Name = "Revue de Cas Complexe"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000019"),
                            Name = "Consultation Préopératoire"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000020"),
                            Name = "Suivi Postopératoire"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000021"),
                            Name = "Consultation Chirurgicale"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000022"),
                            Name = "Gestion des Plaies"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000023"),
                            Name = "Consultation Articulaire"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000024"),
                            Name = "Évaluation des Blessures Sportives"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000025"),
                            Name = "Gestion des Fractures"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000026"),
                            Name = "Retrait de Plâtre"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000027"),
                            Name = "Évaluation Neurologique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000028"),
                            Name = "Gestion de la Douleur"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000029"),
                            Name = "Consultation Esthétique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000030"),
                            Name = "Consultation Reconstructive"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000031"),
                            Name = "Révision de Cicatrice"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000032"),
                            Name = "Consultation Cardiaque"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000033"),
                            Name = "Évaluation des Risques"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000034"),
                            Name = "Évaluation Urologique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000035"),
                            Name = "Dépistage de la Prostate"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000036"),
                            Name = "Gestion des Calculs Rénaux"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000037"),
                            Name = "Évaluation de la Vessie"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000038"),
                            Name = "Interprétation Radiographique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000039"),
                            Name = "Consultation Scanner (CT)"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000040"),
                            Name = "Consultation IRM"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000041"),
                            Name = "Consultation Échographie"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000042"),
                            Name = "Revue de Mammographie"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000043"),
                            Name = "Procédure Guidée par l'Image"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000044"),
                            Name = "Revue de Biopsie"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000045"),
                            Name = "Consultation Résultats Labo"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000046"),
                            Name = "Revue Cytologique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000047"),
                            Name = "Consultation Histopathologique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000048"),
                            Name = "Évaluation Traumatologique"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000049"),
                            Name = "Soins Aigus"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000050"),
                            Name = "Urgence Mineure"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000051"),
                            Name = "Consultation USI"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000052"),
                            Name = "Évaluation Soins Critiques"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000053"),
                            Name = "Gestion Ventilateur"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000054"),
                            Name = "Réunion Familiale"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000055"),
                            Name = "Visite Prénatale"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000056"),
                            Name = "Bilan Postnatal"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000057"),
                            Name = "Échographie"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000058"),
                            Name = "Frottis Cervico-vaginal"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000059"),
                            Name = "Planification Familiale"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000060"),
                            Name = "Consultation Fertilité"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000061"),
                            Name = "Gestion de la Ménopause"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000062"),
                            Name = "Évaluation de la Croissance"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000063"),
                            Name = "Prise de Tension"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000064"),
                            Name = "Éducation Santé"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000065"),
                            Name = "Visite à Domicile"
                        });
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.VerificationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_url");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_verification_documents");

                    b.HasIndex("ProfessionalId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_documents_professional_id_type");

                    b.ToTable("verification_documents", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("EndYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("end_year");

                    b.Property<bool>("IsCurrentPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_position");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("organization");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("start_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_experiences");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_work_experiences_professional_id");

                    b.ToTable("work_experiences", "professionals");
                });

            modelBuilder.Entity("professional_services", b =>
                {
                    b.Property<Guid>("professional_id")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid>("service_id")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("professional_id", "service_id")
                        .HasName("pk_professional_services");

                    b.HasIndex("service_id")
                        .HasDatabaseName("ix_professional_services_service_id");

                    b.ToTable("professional_services", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("AvailabilityDays")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_days_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.AvailabilityDay", "Day")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("AvailabilityDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_slots_availability_days_availability_day_id");

                    b.OwnsOne("Modules.Common.Features.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("AvailabilitySlotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.HasKey("AvailabilitySlotId");

                            b1.ToTable("availability_slots", "professionals");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilitySlotId")
                                .HasConstraintName("fk_availability_slots_availability_slots_id");
                        });

                    b.Navigation("Day");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Award", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("Awards")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_awards_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Education", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("Educations")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educations_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.VerificationDocument", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("VerificationDocuments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_documents_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_experiences_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("professional_services", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", null)
                        .WithMany()
                        .HasForeignKey("professional_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professional_services_professionals_professional_id");

                    b.HasOne("Modules.Professionals.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professional_services_services_service_id");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Navigation("AvailabilityDays");

                    b.Navigation("Awards");

                    b.Navigation("Educations");

                    b.Navigation("VerificationDocuments");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
