// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Professionals.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Professionals.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProfessionalsDbContext))]
    partial class ProfessionalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("professionals")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_days");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_availability_days_professional_id");

                    b.ToTable("availability_days", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvailabilityDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_day_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_slots");

                    b.HasIndex("AvailabilityDayId")
                        .HasDatabaseName("ix_availability_slots_availability_day_id");

                    b.ToTable("availability_slots", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EndPrice")
                        .HasColumnType("integer")
                        .HasColumnName("end_price");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.PrimitiveCollection<List<string>>("Services")
                        .HasColumnType("text[]")
                        .HasColumnName("services");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<int?>("StartPrice")
                        .HasColumnType("integer")
                        .HasColumnName("start_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_professionals");

                    b.ToTable("professionals", "professionals");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.Professional", "Professional")
                        .WithMany("AvailabilityDays")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_days_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("Modules.Professionals.Domain.Entities.AvailabilityDay", "Day")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("AvailabilityDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_slots_availability_days_availability_day_id");

                    b.OwnsOne("Modules.Common.Features.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("AvailabilitySlotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.HasKey("AvailabilitySlotId");

                            b1.ToTable("availability_slots", "professionals");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilitySlotId")
                                .HasConstraintName("fk_availability_slots_availability_slots_id");
                        });

                    b.Navigation("Day");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.AvailabilityDay", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("Modules.Professionals.Domain.Entities.Professional", b =>
                {
                    b.Navigation("AvailabilityDays");
                });
#pragma warning restore 612, 618
        }
    }
}
