export interface SelectItem {
  value: string;
  label: string;
}

const COMMON_SERVICES: SelectItem[] = [
  { label: "Consultation Initiale", value: "initialConsultation" },
  { label: "Visite de Suivi", value: "followUpVisit" },
  { label: "Téléconsultation", value: "telehealthConsultation" },
  { label: "Consultation d'Urgence", value: "emergencyConsultation" },
  { label: "Deuxième Avis", value: "secondOpinion" },
  { label: "Renouvellement d'Ordonnance", value: "prescriptionRefill" },
  { label: "Certificat Médical", value: "medicalCertificate" },
  { label: "Bilan de Santé", value: "healthCheckup" },
];

export const SERVICES: Record<string, SelectItem[]> = {
  generalPractitioner: [
    ...COMMON_SERVICES,
    { label: "Vaccination", value: "vaccination" },
    { label: "Procédure Mineure", value: "minorProcedure" },
    { label: "Soins des Plaies", value: "woundCare" },
    { label: "Médecine des Voyages", value: "travelMedicine" },
  ],
  familyMedicine: [
    ...COMMON_SERVICES,
    { label: "Vaccination", value: "vaccination" },
    { label: "Visite de l'Enfant Sain", value: "wellChildVisit" },
    { label: "Gestion des Maladies Chroniques", value: "chronicDiseaseManagement" },
    { label: "Soins Préventifs", value: "preventiveCare" },
  ],
  internalMedicine: [
    ...COMMON_SERVICES,
    { label: "Gestion des Maladies Chroniques", value: "chronicDiseaseManagement" },
    { label: "Consultation Diagnostique", value: "diagnosticConsultation" },
    { label: "Évaluation Préopératoire", value: "preOperativeAssessment" },
    { label: "Revue de Cas Complexe", value: "complexCaseReview" },
  ],
  generalSurgery: [
    ...COMMON_SERVICES,
    { label: "Consultation Préopératoire", value: "preOperativeConsultation" },
    { label: "Suivi Postopératoire", value: "postOperativeFollowUp" },
    { label: "Consultation Chirurgicale", value: "surgicalConsultation" },
    { label: "Gestion des Plaies", value: "woundManagement" },
  ],
  orthopedicSurgery: [
    ...COMMON_SERVICES,
    { label: "Consultation Articulaire", value: "jointConsultation" },
    { label: "Évaluation des Blessures Sportives", value: "sportsInjuryAssessment" },
    { label: "Consultation Préopératoire", value: "preOperativeConsultation" },
    { label: "Suivi Postopératoire", value: "postOperativeFollowUp" },
    { label: "Gestion des Fractures", value: "fractureManagement" },
    { label: "Retrait de Plâtre", value: "castRemoval" },
  ],
  neurosurgery: [
    ...COMMON_SERVICES,
    { label: "Évaluation Neurologique", value: "neurologicalAssessment" },
    { label: "Consultation Préopératoire", value: "preOperativeConsultation" },
    { label: "Suivi Postopératoire", value: "postOperativeFollowUp" },
    { label: "Gestion de la Douleur", value: "painManagement" },
  ],
  plasticSurgery: [
    ...COMMON_SERVICES,
    { label: "Consultation Esthétique", value: "cosmeticConsultation" },
    {
      label: "Consultation Reconstructive",
      value: "reconstructiveConsultation",
    },
    { label: "Consultation Préopératoire", value: "preOperativeConsultation" },
    { label: "Suivi Postopératoire", value: "postOperativeFollowUp" },
    { label: "Révision de Cicatrice", value: "scarRevision" },
  ],
  cardiothoracicSurgery: [
    ...COMMON_SERVICES,
    { label: "Consultation Cardiaque", value: "cardiacConsultation" },
    { label: "Consultation Préopératoire", value: "preOperativeConsultation" },
    { label: "Suivi Postopératoire", value: "postOperativeFollowUp" },
    { label: "Évaluation des Risques", value: "riskAssessment" },
  ],
  urology: [
    ...COMMON_SERVICES,
    { label: "Évaluation Urologique", value: "urologicalAssessment" },
    { label: "Dépistage de la Prostate", value: "prostateScreening" },
    { label: "Gestion des Calculs Rénaux", value: "kidneyStoneManagement" },
    { label: "Évaluation de la Vessie", value: "bladderAssessment" },
  ],
  radiology: [
    { label: "Interprétation Radiographique", value: "xrayInterpretation" },
    { label: "Consultation Scanner (CT)", value: "ctScanConsultation" },
    { label: "Consultation IRM", value: "mriConsultation" },
    { label: "Consultation Échographie", value: "ultrasoundConsultation" },
    { label: "Revue de Mammographie", value: "mammographyReview" },
    { label: "Procédure Guidée par l'Image", value: "imageGuidedProcedure" },
  ],
  pathology: [
    { label: "Revue de Biopsie", value: "biopsyReview" },
    { label: "Consultation Résultats Labo", value: "labResultsConsultation" },
    { label: "Revue Cytologique", value: "cytologyReview" },
    {
      label: "Consultation Histopathologique",
      value: "histopathologyConsultation",
    },
  ],
  emergencyMedicine: [
    { label: "Consultation d'Urgence", value: "emergencyConsultation" },
    { label: "Évaluation Traumatologique", value: "traumaAssessment" },
    { label: "Soins Aigus", value: "acuteCare" },
    { label: "Urgence Mineure", value: "minorEmergency" },
  ],
  criticalCare: [
    { label: "Consultation USI", value: "icuConsultation" },
    { label: "Évaluation Soins Critiques", value: "criticalCareAssessment" },
    { label: "Gestion Ventilateur", value: "ventilatorManagement" },
    { label: "Réunion Familiale", value: "familyMeeting" },
  ],
  obstetricsAndGynecology: [
    ...COMMON_SERVICES,
    { label: "Visite Prénatale", value: "prenatalVisit" },
    { label: "Bilan Postnatal", value: "postnatalCheckup" },
    { label: "Échographie", value: "ultrasoundScan" },
    { label: "Frottis Cervico-vaginal", value: "papSmear" },
    { label: "Planification Familiale", value: "familyPlanning" },
    { label: "Consultation Fertilité", value: "fertilityConsultation" },
    { label: "Gestion de la Ménopause", value: "menopauseManagement" },
  ],
  pediatrics: [
    ...COMMON_SERVICES,
    { label: "Visite de l'Enfant Sain", value: "wellChildVisit" },
    { label: "Vaccination", value: "vaccination" },
    { label: "Évaluation de la Croissance", value: "growthAssessment" },
    { label: "Dépistage Développemental", value: "developmentalScreening" },
    { label: "Bilan Nouveau-né", value: "newbornCheckup" },
  ],
  psychiatry: [
    ...COMMON_SERVICES,
    { label: "Évaluation Psychiatrique", value: "psychiatricEvaluation" },
    { label: "Gestion des Médicaments", value: "medicationManagement" },
    { label: "Séance de Thérapie", value: "therapySession" },
    { label: "Intervention de Crise", value: "crisisIntervention" },
    { label: "Thérapie Familiale", value: "familyTherapy" },
  ],
  psychology: [
    { label: "Évaluation Initiale", value: "initialAssessment" },
    { label: "Thérapie Individuelle", value: "individualTherapy" },
    { label: "Thérapie de Couple", value: "couplesTherapy" },
    { label: "Thérapie Familiale", value: "familyTherapy" },
    { label: "Thérapie de Groupe", value: "groupTherapy" },
    {
      label: "Thérapie Cognitivo-Comportementale",
      value: "cognitiveBehavioralTherapy",
    },
    { label: "Tests Psychologiques", value: "psychologicalTesting" },
  ],
  cardiology: [
    ...COMMON_SERVICES,
    { label: "Consultation ECG", value: "ecgConsultation" },
    { label: "Revue Échocardiogramme", value: "echocardiogramReview" },
    { label: "Test d'Effort", value: "stressTest" },
    { label: "Gestion Maladie Cardiaque", value: "heartDiseaseManagement" },
    { label: "Gestion Hypertension", value: "hypertensionManagement" },
    { label: "Suivi Pacemaker", value: "pacemakerFollowUp" },
  ],
  pulmonology: [
    ...COMMON_SERVICES,
    { label: "Test Fonction Pulmonaire", value: "lungFunctionTest" },
    { label: "Gestion Asthme", value: "asthmaManagement" },
    { label: "Gestion BPCO", value: "copdManagement" },
    { label: "Consultation Apnée du Sommeil", value: "sleepApneaConsultation" },
    { label: "Suivi Bronchoscopie", value: "bronchoscopyFollowUp" },
  ],
  gastroenterology: [
    ...COMMON_SERVICES,
    { label: "Consultation Endoscopie", value: "endoscopyConsultation" },
    { label: "Consultation Colonoscopie", value: "colonoscopyConsultation" },
    { label: "Gestion Maladie Hépatique", value: "liverDiseaseManagement" },
    { label: "Gestion SII", value: "ibsManagement" },
    { label: "Gestion Mici", value: "ibdManagement" },
  ],
  nephrology: [
    ...COMMON_SERVICES,
    { label: "Gestion Maladie Rénale", value: "kidneyDiseaseManagement" },
    { label: "Consultation Dialyse", value: "dialysisConsultation" },
    { label: "Gestion Calculs Rénaux", value: "kidneyStoneManagement" },
    { label: "Gestion Hypertension", value: "hypertensionManagement" },
    { label: "Suivi Transplantation", value: "transplantFollowUp" },
  ],
  endocrinology: [
    ...COMMON_SERVICES,
    { label: "Gestion Diabète", value: "diabetesManagement" },
    { label: "Consultation Thyroïde", value: "thyroidConsultation" },
    { label: "Hormonothérapie", value: "hormoneTherapy" },
    {
      label: "Gestion Troubles Métaboliques",
      value: "metabolicDisorderManagement",
    },
    { label: "Gestion Ostéoporose", value: "osteoporosisManagement" },
  ],
  dermatology: [
    ...COMMON_SERVICES,
    { label: "Examen Cutané", value: "skinExamination" },
    { label: "Traitement Acné", value: "acneTreatment" },
    { label: "Vérification Grains de Beauté", value: "moleCheck" },
    { label: "Procédure Esthétique", value: "cosmeticProcedure" },
    { label: "Tests Allergiques", value: "allergyTesting" },
    { label: "Traitement Laser", value: "laserTreatment" },
  ],
  ophthalmology: [
    ...COMMON_SERVICES,
    { label: "Examen Oculaire", value: "eyeExamination" },
    { label: "Test de Vision", value: "visionTest" },
    { label: "Consultation Cataracte", value: "cataractConsultation" },
    { label: "Dépistage Glaucome", value: "glaucomaScreening" },
    { label: "Adaptation Lentilles", value: "contactLensFitting" },
    { label: "Examen Rétinien", value: "retinalExamination" },
  ],
  ent: [
    ...COMMON_SERVICES,
    { label: "Test Auditif", value: "hearingTest" },
    { label: "Examen Gorge", value: "throatExamination" },
    { label: "Endoscopie Nasale", value: "nasalEndoscopy" },
    { label: "Tests Allergiques", value: "allergyTesting" },
    { label: "Évaluation Équilibre", value: "balanceAssessment" },
    { label: "Évaluation Vocale", value: "voiceAssessment" },
  ],
  dentistry: [
    { label: "Bilan Dentaire", value: "dentalCheckup" },
    { label: "Détartrage", value: "teethCleaning" },
    { label: "Plombage", value: "filling" },
    { label: "Traitement de Canal", value: "rootCanal" },
    { label: "Extraction Dentaire", value: "toothExtraction" },
    { label: "Consultation Orthodontique", value: "orthodonticConsultation" },
    { label: "Dentisterie Esthétique", value: "cosmeticDentistry" },
    { label: "Soins Dentaires d'Urgence", value: "emergencyDentalCare" },
  ],
  physiotherapy: [
    { label: "Évaluation Initiale", value: "initialAssessment" },
    { label: "Séance de Suivi", value: "followUpSession" },
    { label: "Traitement Blessure Sportive", value: "sportsInjuryTreatment" },
    {
      label: "Rééducation Postopératoire",
      value: "postOperativeRehabilitation",
    },
    { label: "Gestion de la Douleur", value: "painManagement" },
    { label: "Prescription d'Exercices", value: "exercisePrescription" },
    { label: "Thérapie Manuelle", value: "manualTherapy" },
  ],
  pharmacy: [
    { label: "Revue Médicamenteuse", value: "medicationReview" },
    { label: "Consultation Ordonnance", value: "prescriptionConsultation" },
    { label: "Vaccination", value: "vaccination" },
    { label: "Dépistage Santé", value: "healthScreening" },
    {
      label: "Gestion Thérapie Médicamenteuse",
      value: "medicationTherapyManagement",
    },
  ],
  nursing: [
    { label: "Soins des Plaies", value: "woundCare" },
    { label: "Administration Injection", value: "injectionAdministration" },
    { label: "Prise de Tension", value: "bloodPressureCheck" },
    { label: "Éducation Santé", value: "healthEducation" },
    { label: "Visite à Domicile", value: "homeVisit" },
  ],
  other: COMMON_SERVICES,
};

export const getServicesForSpecialization = (
  specialization: string,
): SelectItem[] => {
  return SERVICES[specialization] || COMMON_SERVICES;
};
