export interface SelectItem {
  value: string;
  label: string;
}

const COMMON_SERVICES: SelectItem[] = [
  { label: "Initial Consultation", value: "initialConsultation" },
  { label: "Follow-up Visit", value: "followUpVisit" },
  { label: "Telehealth Consultation", value: "telehealthConsultation" },
  { label: "Emergency Consultation", value: "emergencyConsultation" },
  { label: "Second Opinion", value: "secondOpinion" },
  { label: "Prescription Refill", value: "prescriptionRefill" },
  { label: "Medical Certificate", value: "medicalCertificate" },
  { label: "Health Check-up", value: "healthCheckup" },
];

export const SERVICES: Record<string, SelectItem[]> = {
  generalPractitioner: [
    ...COMMON_SERVICES,
    { label: "Vaccination", value: "vaccination" },
    { label: "Minor Procedure", value: "minorProcedure" },
    { label: "Wound Care", value: "woundCare" },
    { label: "Travel Medicine", value: "travelMedicine" },
  ],
  familyMedicine: [
    ...COMMON_SERVICES,
    { label: "Vaccination", value: "vaccination" },
    { label: "Well-Child Visit", value: "wellChildVisit" },
    { label: "Chronic Disease Management", value: "chronicDiseaseManagement" },
    { label: "Preventive Care", value: "preventiveCare" },
  ],
  internalMedicine: [
    ...COMMON_SERVICES,
    { label: "Chronic Disease Management", value: "chronicDiseaseManagement" },
    { label: "Diagnostic Consultation", value: "diagnosticConsultation" },
    { label: "Pre-operative Assessment", value: "preOperativeAssessment" },
    { label: "Complex Case Review", value: "complexCaseReview" },
  ],
  generalSurgery: [
    ...COMMON_SERVICES,
    { label: "Pre-operative Consultation", value: "preOperativeConsultation" },
    { label: "Post-operative Follow-up", value: "postOperativeFollowUp" },
    { label: "Surgical Consultation", value: "surgicalConsultation" },
    { label: "Wound Management", value: "woundManagement" },
  ],
  orthopedicSurgery: [
    ...COMMON_SERVICES,
    { label: "Joint Consultation", value: "jointConsultation" },
    { label: "Sports Injury Assessment", value: "sportsInjuryAssessment" },
    { label: "Pre-operative Consultation", value: "preOperativeConsultation" },
    { label: "Post-operative Follow-up", value: "postOperativeFollowUp" },
    { label: "Fracture Management", value: "fractureManagement" },
    { label: "Cast Removal", value: "castRemoval" },
  ],
  neurosurgery: [
    ...COMMON_SERVICES,
    { label: "Neurological Assessment", value: "neurologicalAssessment" },
    { label: "Pre-operative Consultation", value: "preOperativeConsultation" },
    { label: "Post-operative Follow-up", value: "postOperativeFollowUp" },
    { label: "Pain Management", value: "painManagement" },
  ],
  plasticSurgery: [
    ...COMMON_SERVICES,
    { label: "Cosmetic Consultation", value: "cosmeticConsultation" },
    {
      label: "Reconstructive Consultation",
      value: "reconstructiveConsultation",
    },
    { label: "Pre-operative Consultation", value: "preOperativeConsultation" },
    { label: "Post-operative Follow-up", value: "postOperativeFollowUp" },
    { label: "Scar Revision", value: "scarRevision" },
  ],
  cardiothoracicSurgery: [
    ...COMMON_SERVICES,
    { label: "Cardiac Consultation", value: "cardiacConsultation" },
    { label: "Pre-operative Consultation", value: "preOperativeConsultation" },
    { label: "Post-operative Follow-up", value: "postOperativeFollowUp" },
    { label: "Risk Assessment", value: "riskAssessment" },
  ],
  urology: [
    ...COMMON_SERVICES,
    { label: "Urological Assessment", value: "urologicalAssessment" },
    { label: "Prostate Screening", value: "prostateScreening" },
    { label: "Kidney Stone Management", value: "kidneyStoneManagement" },
    { label: "Bladder Assessment", value: "bladderAssessment" },
  ],
  radiology: [
    { label: "X-ray Interpretation", value: "xrayInterpretation" },
    { label: "CT Scan Consultation", value: "ctScanConsultation" },
    { label: "MRI Consultation", value: "mriConsultation" },
    { label: "Ultrasound Consultation", value: "ultrasoundConsultation" },
    { label: "Mammography Review", value: "mammographyReview" },
    { label: "Image-guided Procedure", value: "imageGuidedProcedure" },
  ],
  pathology: [
    { label: "Biopsy Review", value: "biopsyReview" },
    { label: "Lab Results Consultation", value: "labResultsConsultation" },
    { label: "Cytology Review", value: "cytologyReview" },
    {
      label: "Histopathology Consultation",
      value: "histopathologyConsultation",
    },
  ],
  emergencyMedicine: [
    { label: "Emergency Consultation", value: "emergencyConsultation" },
    { label: "Trauma Assessment", value: "traumaAssessment" },
    { label: "Acute Care", value: "acuteCare" },
    { label: "Minor Emergency", value: "minorEmergency" },
  ],
  criticalCare: [
    { label: "ICU Consultation", value: "icuConsultation" },
    { label: "Critical Care Assessment", value: "criticalCareAssessment" },
    { label: "Ventilator Management", value: "ventilatorManagement" },
    { label: "Family Meeting", value: "familyMeeting" },
  ],
  obstetricsAndGynecology: [
    ...COMMON_SERVICES,
    { label: "Prenatal Visit", value: "prenatalVisit" },
    { label: "Postnatal Check-up", value: "postnatalCheckup" },
    { label: "Ultrasound Scan", value: "ultrasoundScan" },
    { label: "Pap Smear", value: "papSmear" },
    { label: "Family Planning", value: "familyPlanning" },
    { label: "Fertility Consultation", value: "fertilityConsultation" },
    { label: "Menopause Management", value: "menopauseManagement" },
  ],
  pediatrics: [
    ...COMMON_SERVICES,
    { label: "Well-Child Visit", value: "wellChildVisit" },
    { label: "Vaccination", value: "vaccination" },
    { label: "Growth Assessment", value: "growthAssessment" },
    { label: "Developmental Screening", value: "developmentalScreening" },
    { label: "Newborn Check-up", value: "newbornCheckup" },
  ],
  psychiatry: [
    ...COMMON_SERVICES,
    { label: "Psychiatric Evaluation", value: "psychiatricEvaluation" },
    { label: "Medication Management", value: "medicationManagement" },
    { label: "Therapy Session", value: "therapySession" },
    { label: "Crisis Intervention", value: "crisisIntervention" },
    { label: "Family Therapy", value: "familyTherapy" },
  ],
  psychology: [
    { label: "Initial Assessment", value: "initialAssessment" },
    { label: "Individual Therapy", value: "individualTherapy" },
    { label: "Couples Therapy", value: "couplesTherapy" },
    { label: "Family Therapy", value: "familyTherapy" },
    { label: "Group Therapy", value: "groupTherapy" },
    {
      label: "Cognitive Behavioral Therapy",
      value: "cognitiveBehavioralTherapy",
    },
    { label: "Psychological Testing", value: "psychologicalTesting" },
  ],
  cardiology: [
    ...COMMON_SERVICES,
    { label: "ECG Consultation", value: "ecgConsultation" },
    { label: "Echocardiogram Review", value: "echocardiogramReview" },
    { label: "Stress Test", value: "stressTest" },
    { label: "Heart Disease Management", value: "heartDiseaseManagement" },
    { label: "Hypertension Management", value: "hypertensionManagement" },
    { label: "Pacemaker Follow-up", value: "pacemakerFollowUp" },
  ],
  pulmonology: [
    ...COMMON_SERVICES,
    { label: "Lung Function Test", value: "lungFunctionTest" },
    { label: "Asthma Management", value: "asthmaManagement" },
    { label: "COPD Management", value: "copdManagement" },
    { label: "Sleep Apnea Consultation", value: "sleepApneaConsultation" },
    { label: "Bronchoscopy Follow-up", value: "bronchoscopyFollowUp" },
  ],
  gastroenterology: [
    ...COMMON_SERVICES,
    { label: "Endoscopy Consultation", value: "endoscopyConsultation" },
    { label: "Colonoscopy Consultation", value: "colonoscopyConsultation" },
    { label: "Liver Disease Management", value: "liverDiseaseManagement" },
    { label: "IBS Management", value: "ibsManagement" },
    { label: "IBD Management", value: "ibdManagement" },
  ],
  nephrology: [
    ...COMMON_SERVICES,
    { label: "Kidney Disease Management", value: "kidneyDiseaseManagement" },
    { label: "Dialysis Consultation", value: "dialysisConsultation" },
    { label: "Kidney Stone Management", value: "kidneyStoneManagement" },
    { label: "Hypertension Management", value: "hypertensionManagement" },
    { label: "Transplant Follow-up", value: "transplantFollowUp" },
  ],
  endocrinology: [
    ...COMMON_SERVICES,
    { label: "Diabetes Management", value: "diabetesManagement" },
    { label: "Thyroid Consultation", value: "thyroidConsultation" },
    { label: "Hormone Therapy", value: "hormoneTherapy" },
    {
      label: "Metabolic Disorder Management",
      value: "metabolicDisorderManagement",
    },
    { label: "Osteoporosis Management", value: "osteoporosisManagement" },
  ],
  dermatology: [
    ...COMMON_SERVICES,
    { label: "Skin Examination", value: "skinExamination" },
    { label: "Acne Treatment", value: "acneTreatment" },
    { label: "Mole Check", value: "moleCheck" },
    { label: "Cosmetic Procedure", value: "cosmeticProcedure" },
    { label: "Allergy Testing", value: "allergyTesting" },
    { label: "Laser Treatment", value: "laserTreatment" },
  ],
  ophthalmology: [
    ...COMMON_SERVICES,
    { label: "Eye Examination", value: "eyeExamination" },
    { label: "Vision Test", value: "visionTest" },
    { label: "Cataract Consultation", value: "cataractConsultation" },
    { label: "Glaucoma Screening", value: "glaucomaScreening" },
    { label: "Contact Lens Fitting", value: "contactLensFitting" },
    { label: "Retinal Examination", value: "retinalExamination" },
  ],
  ent: [
    ...COMMON_SERVICES,
    { label: "Hearing Test", value: "hearingTest" },
    { label: "Throat Examination", value: "throatExamination" },
    { label: "Nasal Endoscopy", value: "nasalEndoscopy" },
    { label: "Allergy Testing", value: "allergyTesting" },
    { label: "Balance Assessment", value: "balanceAssessment" },
    { label: "Voice Assessment", value: "voiceAssessment" },
  ],
  dentistry: [
    { label: "Dental Check-up", value: "dentalCheckup" },
    { label: "Teeth Cleaning", value: "teethCleaning" },
    { label: "Filling", value: "filling" },
    { label: "Root Canal", value: "rootCanal" },
    { label: "Tooth Extraction", value: "toothExtraction" },
    { label: "Orthodontic Consultation", value: "orthodonticConsultation" },
    { label: "Cosmetic Dentistry", value: "cosmeticDentistry" },
    { label: "Emergency Dental Care", value: "emergencyDentalCare" },
  ],
  physiotherapy: [
    { label: "Initial Assessment", value: "initialAssessment" },
    { label: "Follow-up Session", value: "followUpSession" },
    { label: "Sports Injury Treatment", value: "sportsInjuryTreatment" },
    {
      label: "Post-operative Rehabilitation",
      value: "postOperativeRehabilitation",
    },
    { label: "Pain Management", value: "painManagement" },
    { label: "Exercise Prescription", value: "exercisePrescription" },
    { label: "Manual Therapy", value: "manualTherapy" },
  ],
  pharmacy: [
    { label: "Medication Review", value: "medicationReview" },
    { label: "Prescription Consultation", value: "prescriptionConsultation" },
    { label: "Vaccination", value: "vaccination" },
    { label: "Health Screening", value: "healthScreening" },
    {
      label: "Medication Therapy Management",
      value: "medicationTherapyManagement",
    },
  ],
  nursing: [
    { label: "Wound Care", value: "woundCare" },
    { label: "Injection Administration", value: "injectionAdministration" },
    { label: "Blood Pressure Check", value: "bloodPressureCheck" },
    { label: "Health Education", value: "healthEducation" },
    { label: "Home Visit", value: "homeVisit" },
  ],
  other: COMMON_SERVICES,
};

export const getServicesForSpecialization = (
  specialization: string,
): SelectItem[] => {
  return SERVICES[specialization] || COMMON_SERVICES;
};
