// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Patients.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Patients.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    partial class PatientsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_allergies");

                    b.ToTable("allergies", "patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000001"),
                            Key = "allergies.peanuts"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000002"),
                            Key = "allergies.treeNuts"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000003"),
                            Key = "allergies.milk"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000004"),
                            Key = "allergies.egg"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000005"),
                            Key = "allergies.wheat"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000006"),
                            Key = "allergies.soy"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000007"),
                            Key = "allergies.fish"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000008"),
                            Key = "allergies.shellfish"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000009"),
                            Key = "allergies.sesame"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000010"),
                            Key = "allergies.penicillin"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000011"),
                            Key = "allergies.latex"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000012"),
                            Key = "allergies.pollen"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000013"),
                            Key = "allergies.dustMites"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000014"),
                            Key = "allergies.petDander"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000015"),
                            Key = "allergies.insectStings"
                        });
                });

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_conditions");

                    b.ToTable("conditions", "patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000001"),
                            Key = "conditions.hypertension"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000002"),
                            Key = "conditions.diabetesType1"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000003"),
                            Key = "conditions.diabetesType2"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000004"),
                            Key = "conditions.asthma"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000005"),
                            Key = "conditions.arthritis"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000006"),
                            Key = "conditions.heartDisease"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000007"),
                            Key = "conditions.copd"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000008"),
                            Key = "conditions.depression"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000009"),
                            Key = "conditions.anxiety"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000010"),
                            Key = "conditions.obesity"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000011"),
                            Key = "conditions.osteoporosis"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000012"),
                            Key = "conditions.chronicKidneyDisease"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000013"),
                            Key = "conditions.alzheimers"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000014"),
                            Key = "conditions.cancer"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000015"),
                            Key = "conditions.stroke"
                        });
                });

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_medications");

                    b.ToTable("medications", "patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000001"),
                            Key = "medications.lisinopril"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000002"),
                            Key = "medications.levothyroxine"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000003"),
                            Key = "medications.atorvastatin"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000004"),
                            Key = "medications.metformin"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000005"),
                            Key = "medications.simvastatin"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000006"),
                            Key = "medications.omeprazole"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000007"),
                            Key = "medications.amlodipine"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000008"),
                            Key = "medications.metoprolol"
                        });
                });

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("MobilityStatus")
                        .HasColumnType("text")
                        .HasColumnName("mobility_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", "patients");
                });

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.ToTable("relationships", "patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Key = "relationships.parent"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000002"),
                            Key = "relationships.child"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000003"),
                            Key = "relationships.spouse"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000004"),
                            Key = "relationships.partner"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Key = "relationships.sibling"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000006"),
                            Key = "relationships.grandparent"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000007"),
                            Key = "relationships.grandchild"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000008"),
                            Key = "relationships.relative"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000009"),
                            Key = "relationships.friend"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000010"),
                            Key = "relationships.neighbor"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000011"),
                            Key = "relationships.caregiver"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000012"),
                            Key = "relationships.guardian"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000013"),
                            Key = "relationships.doctor"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000014"),
                            Key = "relationships.nurse"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000015"),
                            Key = "relationships.colleague"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000016"),
                            Key = "relationships.other"
                        });
                });

            modelBuilder.Entity("patient_allergies", b =>
                {
                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("allergy_id")
                        .HasColumnType("uuid")
                        .HasColumnName("allergy_id");

                    b.HasKey("patient_id", "allergy_id")
                        .HasName("pk_patient_allergies");

                    b.HasIndex("allergy_id")
                        .HasDatabaseName("ix_patient_allergies_allergy_id");

                    b.ToTable("patient_allergies", "patients");
                });

            modelBuilder.Entity("patient_conditions", b =>
                {
                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("condition_id")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_id");

                    b.HasKey("patient_id", "condition_id")
                        .HasName("pk_patient_conditions");

                    b.HasIndex("condition_id")
                        .HasDatabaseName("ix_patient_conditions_condition_id");

                    b.ToTable("patient_conditions", "patients");
                });

            modelBuilder.Entity("patient_medications", b =>
                {
                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("medication_id")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.HasKey("patient_id", "medication_id")
                        .HasName("pk_patient_medications");

                    b.HasIndex("medication_id")
                        .HasDatabaseName("ix_patient_medications_medication_id");

                    b.ToTable("patient_medications", "patients");
                });

            modelBuilder.Entity("Modules.Patients.Domain.Entities.Patient", b =>
                {
                    b.OwnsOne("Modules.Patients.Domain.ValueObjects.EmergencyContact", "EmergencyContact", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("emergency_contact_full_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("emergency_contact_phone_number");

                            b1.Property<Guid?>("RelationshipId")
                                .HasColumnType("uuid")
                                .HasColumnName("emergency_contact_relationship_id");

                            b1.HasKey("PatientId");

                            b1.ToTable("patients", "patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId")
                                .HasConstraintName("fk_patients_patients_id");
                        });

                    b.Navigation("EmergencyContact")
                        .IsRequired();
                });

            modelBuilder.Entity("patient_allergies", b =>
                {
                    b.HasOne("Modules.Patients.Domain.Entities.Allergy", null)
                        .WithMany()
                        .HasForeignKey("allergy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergies_allergies_allergy_id");

                    b.HasOne("Modules.Patients.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergies_patients_patient_id");
                });

            modelBuilder.Entity("patient_conditions", b =>
                {
                    b.HasOne("Modules.Patients.Domain.Entities.Condition", null)
                        .WithMany()
                        .HasForeignKey("condition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_conditions_conditions_condition_id");

                    b.HasOne("Modules.Patients.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_conditions_patients_patient_id");
                });

            modelBuilder.Entity("patient_medications", b =>
                {
                    b.HasOne("Modules.Patients.Domain.Entities.Medication", null)
                        .WithMany()
                        .HasForeignKey("medication_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_medications_medications_medication_id");

                    b.HasOne("Modules.Patients.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_medications_patients_patient_id");
                });
#pragma warning restore 612, 618
        }
    }
}
