/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessionalRouteRouteImport } from './routes/professional/route'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalIndexRouteImport } from './routes/professional/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfessionalSettingsRouteImport } from './routes/professional/settings'
import { Route as ProfessionalScheduleTimingsRouteImport } from './routes/professional/schedule-timings'
import { Route as ProfessionalProfileRouteImport } from './routes/professional/profile'
import { Route as ProfessionalPaymentRouteImport } from './routes/professional/payment'
import { Route as ProfessionalNotificationsRouteImport } from './routes/professional/notifications'
import { Route as ProfessionalMyPatientsRouteImport } from './routes/professional/my-patients'
import { Route as ProfessionalMessagesRouteImport } from './routes/professional/messages'
import { Route as ProfessionalInvoicesRouteImport } from './routes/professional/invoices'
import { Route as ProfessionalAppointmentsRouteImport } from './routes/professional/appointments'
import { Route as PatientSettingsRouteImport } from './routes/patient/settings'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient/prescriptions'
import { Route as PatientNotificationsRouteImport } from './routes/patient/notifications'
import { Route as PatientMyProfessionalsRouteImport } from './routes/patient/my-professionals'
import { Route as PatientMessagesRouteImport } from './routes/patient/messages'
import { Route as PatientFindProfessionalRouteImport } from './routes/patient/find-professional'
import { Route as PatientBillingRouteImport } from './routes/patient/billing'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerifiedRouteImport } from './routes/auth/email-verified'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminProfessionalsIndexRouteImport } from './routes/admin/professionals.index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin/patients.index'
import { Route as ProfessionalPatientPatientIdRouteImport } from './routes/professional/patient.$patientId'
import { Route as PatientProfessionalProfessionalIdRouteImport } from './routes/patient/professional.$professionalId'
import { Route as PatientBookSuccessRouteImport } from './routes/patient/book.success'
import { Route as PatientBookProfessionalIdRouteImport } from './routes/patient/book.$professionalId'
import { Route as AdminProfessionalsProfessionalIdRouteImport } from './routes/admin/professionals.$professionalId'
import { Route as AdminPatientsPatientIdRouteImport } from './routes/admin/patients.$patientId'

const ProfessionalRouteRoute = ProfessionalRouteRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfessionalSettingsRoute = ProfessionalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalScheduleTimingsRoute =
  ProfessionalScheduleTimingsRouteImport.update({
    id: '/schedule-timings',
    path: '/schedule-timings',
    getParentRoute: () => ProfessionalRouteRoute,
  } as any)
const ProfessionalProfileRoute = ProfessionalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalPaymentRoute = ProfessionalPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalNotificationsRoute =
  ProfessionalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProfessionalRouteRoute,
  } as any)
const ProfessionalMyPatientsRoute = ProfessionalMyPatientsRouteImport.update({
  id: '/my-patients',
  path: '/my-patients',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalMessagesRoute = ProfessionalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalInvoicesRoute = ProfessionalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const ProfessionalAppointmentsRoute =
  ProfessionalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ProfessionalRouteRoute,
  } as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMyProfessionalsRoute = PatientMyProfessionalsRouteImport.update({
  id: '/my-professionals',
  path: '/my-professionals',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientFindProfessionalRoute = PatientFindProfessionalRouteImport.update({
  id: '/find-professional',
  path: '/find-professional',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerifiedRoute = AuthEmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfessionalsIndexRoute = AdminProfessionalsIndexRouteImport.update({
  id: '/professionals/',
  path: '/professionals/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfessionalPatientPatientIdRoute =
  ProfessionalPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => ProfessionalRouteRoute,
  } as any)
const PatientProfessionalProfessionalIdRoute =
  PatientProfessionalProfessionalIdRouteImport.update({
    id: '/professional/$professionalId',
    path: '/professional/$professionalId',
    getParentRoute: () => PatientRouteRoute,
  } as any)
const PatientBookSuccessRoute = PatientBookSuccessRouteImport.update({
  id: '/book/success',
  path: '/book/success',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientBookProfessionalIdRoute =
  PatientBookProfessionalIdRouteImport.update({
    id: '/book/$professionalId',
    path: '/book/$professionalId',
    getParentRoute: () => PatientRouteRoute,
  } as any)
const AdminProfessionalsProfessionalIdRoute =
  AdminProfessionalsProfessionalIdRouteImport.update({
    id: '/professionals/$professionalId',
    path: '/professionals/$professionalId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPatientsPatientIdRoute = AdminPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/professional': typeof ProfessionalRouteRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/find-professional': typeof PatientFindProfessionalRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/my-professionals': typeof PatientMyProfessionalsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/professional/invoices': typeof ProfessionalInvoicesRoute
  '/professional/messages': typeof ProfessionalMessagesRoute
  '/professional/my-patients': typeof ProfessionalMyPatientsRoute
  '/professional/notifications': typeof ProfessionalNotificationsRoute
  '/professional/payment': typeof ProfessionalPaymentRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/schedule-timings': typeof ProfessionalScheduleTimingsRoute
  '/professional/settings': typeof ProfessionalSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdRoute
  '/admin/professionals/$professionalId': typeof AdminProfessionalsProfessionalIdRoute
  '/patient/book/$professionalId': typeof PatientBookProfessionalIdRoute
  '/patient/book/success': typeof PatientBookSuccessRoute
  '/patient/professional/$professionalId': typeof PatientProfessionalProfessionalIdRoute
  '/professional/patient/$patientId': typeof ProfessionalPatientPatientIdRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/professionals': typeof AdminProfessionalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/find-professional': typeof PatientFindProfessionalRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/my-professionals': typeof PatientMyProfessionalsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/professional/invoices': typeof ProfessionalInvoicesRoute
  '/professional/messages': typeof ProfessionalMessagesRoute
  '/professional/my-patients': typeof ProfessionalMyPatientsRoute
  '/professional/notifications': typeof ProfessionalNotificationsRoute
  '/professional/payment': typeof ProfessionalPaymentRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/schedule-timings': typeof ProfessionalScheduleTimingsRoute
  '/professional/settings': typeof ProfessionalSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/patient': typeof PatientIndexRoute
  '/professional': typeof ProfessionalIndexRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdRoute
  '/admin/professionals/$professionalId': typeof AdminProfessionalsProfessionalIdRoute
  '/patient/book/$professionalId': typeof PatientBookProfessionalIdRoute
  '/patient/book/success': typeof PatientBookSuccessRoute
  '/patient/professional/$professionalId': typeof PatientProfessionalProfessionalIdRoute
  '/professional/patient/$patientId': typeof ProfessionalPatientPatientIdRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/professionals': typeof AdminProfessionalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/professional': typeof ProfessionalRouteRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/find-professional': typeof PatientFindProfessionalRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/my-professionals': typeof PatientMyProfessionalsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/professional/invoices': typeof ProfessionalInvoicesRoute
  '/professional/messages': typeof ProfessionalMessagesRoute
  '/professional/my-patients': typeof ProfessionalMyPatientsRoute
  '/professional/notifications': typeof ProfessionalNotificationsRoute
  '/professional/payment': typeof ProfessionalPaymentRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/schedule-timings': typeof ProfessionalScheduleTimingsRoute
  '/professional/settings': typeof ProfessionalSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdRoute
  '/admin/professionals/$professionalId': typeof AdminProfessionalsProfessionalIdRoute
  '/patient/book/$professionalId': typeof PatientBookProfessionalIdRoute
  '/patient/book/success': typeof PatientBookSuccessRoute
  '/patient/professional/$professionalId': typeof PatientProfessionalProfessionalIdRoute
  '/professional/patient/$patientId': typeof ProfessionalPatientPatientIdRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/professionals/': typeof AdminProfessionalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/patient'
    | '/professional'
    | '/admin/appointments'
    | '/admin/documents'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/find-professional'
    | '/patient/messages'
    | '/patient/my-professionals'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/settings'
    | '/professional/appointments'
    | '/professional/invoices'
    | '/professional/messages'
    | '/professional/my-patients'
    | '/professional/notifications'
    | '/professional/payment'
    | '/professional/profile'
    | '/professional/schedule-timings'
    | '/professional/settings'
    | '/admin/'
    | '/auth/'
    | '/patient/'
    | '/professional/'
    | '/admin/patients/$patientId'
    | '/admin/professionals/$professionalId'
    | '/patient/book/$professionalId'
    | '/patient/book/success'
    | '/patient/professional/$professionalId'
    | '/professional/patient/$patientId'
    | '/admin/patients'
    | '/admin/professionals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/appointments'
    | '/admin/documents'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/find-professional'
    | '/patient/messages'
    | '/patient/my-professionals'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/settings'
    | '/professional/appointments'
    | '/professional/invoices'
    | '/professional/messages'
    | '/professional/my-patients'
    | '/professional/notifications'
    | '/professional/payment'
    | '/professional/profile'
    | '/professional/schedule-timings'
    | '/professional/settings'
    | '/admin'
    | '/auth'
    | '/patient'
    | '/professional'
    | '/admin/patients/$patientId'
    | '/admin/professionals/$professionalId'
    | '/patient/book/$professionalId'
    | '/patient/book/success'
    | '/patient/professional/$professionalId'
    | '/professional/patient/$patientId'
    | '/admin/patients'
    | '/admin/professionals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/patient'
    | '/professional'
    | '/admin/appointments'
    | '/admin/documents'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/find-professional'
    | '/patient/messages'
    | '/patient/my-professionals'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/settings'
    | '/professional/appointments'
    | '/professional/invoices'
    | '/professional/messages'
    | '/professional/my-patients'
    | '/professional/notifications'
    | '/professional/payment'
    | '/professional/profile'
    | '/professional/schedule-timings'
    | '/professional/settings'
    | '/admin/'
    | '/auth/'
    | '/patient/'
    | '/professional/'
    | '/admin/patients/$patientId'
    | '/admin/professionals/$professionalId'
    | '/patient/book/$professionalId'
    | '/patient/book/success'
    | '/patient/professional/$professionalId'
    | '/professional/patient/$patientId'
    | '/admin/patients/'
    | '/admin/professionals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  ProfessionalRouteRoute: typeof ProfessionalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/professional/settings': {
      id: '/professional/settings'
      path: '/settings'
      fullPath: '/professional/settings'
      preLoaderRoute: typeof ProfessionalSettingsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/schedule-timings': {
      id: '/professional/schedule-timings'
      path: '/schedule-timings'
      fullPath: '/professional/schedule-timings'
      preLoaderRoute: typeof ProfessionalScheduleTimingsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/profile': {
      id: '/professional/profile'
      path: '/profile'
      fullPath: '/professional/profile'
      preLoaderRoute: typeof ProfessionalProfileRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/payment': {
      id: '/professional/payment'
      path: '/payment'
      fullPath: '/professional/payment'
      preLoaderRoute: typeof ProfessionalPaymentRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/notifications': {
      id: '/professional/notifications'
      path: '/notifications'
      fullPath: '/professional/notifications'
      preLoaderRoute: typeof ProfessionalNotificationsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/my-patients': {
      id: '/professional/my-patients'
      path: '/my-patients'
      fullPath: '/professional/my-patients'
      preLoaderRoute: typeof ProfessionalMyPatientsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/messages': {
      id: '/professional/messages'
      path: '/messages'
      fullPath: '/professional/messages'
      preLoaderRoute: typeof ProfessionalMessagesRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/invoices': {
      id: '/professional/invoices'
      path: '/invoices'
      fullPath: '/professional/invoices'
      preLoaderRoute: typeof ProfessionalInvoicesRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/professional/appointments': {
      id: '/professional/appointments'
      path: '/appointments'
      fullPath: '/professional/appointments'
      preLoaderRoute: typeof ProfessionalAppointmentsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/my-professionals': {
      id: '/patient/my-professionals'
      path: '/my-professionals'
      fullPath: '/patient/my-professionals'
      preLoaderRoute: typeof PatientMyProfessionalsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/find-professional': {
      id: '/patient/find-professional'
      path: '/find-professional'
      fullPath: '/patient/find-professional'
      preLoaderRoute: typeof PatientFindProfessionalRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verified': {
      id: '/auth/email-verified'
      path: '/email-verified'
      fullPath: '/auth/email-verified'
      preLoaderRoute: typeof AuthEmailVerifiedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/professionals/': {
      id: '/admin/professionals/'
      path: '/professionals'
      fullPath: '/admin/professionals'
      preLoaderRoute: typeof AdminProfessionalsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/professional/patient/$patientId': {
      id: '/professional/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/professional/patient/$patientId'
      preLoaderRoute: typeof ProfessionalPatientPatientIdRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/patient/professional/$professionalId': {
      id: '/patient/professional/$professionalId'
      path: '/professional/$professionalId'
      fullPath: '/patient/professional/$professionalId'
      preLoaderRoute: typeof PatientProfessionalProfessionalIdRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/book/success': {
      id: '/patient/book/success'
      path: '/book/success'
      fullPath: '/patient/book/success'
      preLoaderRoute: typeof PatientBookSuccessRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/book/$professionalId': {
      id: '/patient/book/$professionalId'
      path: '/book/$professionalId'
      fullPath: '/patient/book/$professionalId'
      preLoaderRoute: typeof PatientBookProfessionalIdRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/admin/professionals/$professionalId': {
      id: '/admin/professionals/$professionalId'
      path: '/professionals/$professionalId'
      fullPath: '/admin/professionals/$professionalId'
      preLoaderRoute: typeof AdminProfessionalsProfessionalIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients/$patientId': {
      id: '/admin/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/admin/patients/$patientId'
      preLoaderRoute: typeof AdminPatientsPatientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPatientsPatientIdRoute: typeof AdminPatientsPatientIdRoute
  AdminProfessionalsProfessionalIdRoute: typeof AdminProfessionalsProfessionalIdRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
  AdminProfessionalsIndexRoute: typeof AdminProfessionalsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPatientsPatientIdRoute: AdminPatientsPatientIdRoute,
  AdminProfessionalsProfessionalIdRoute: AdminProfessionalsProfessionalIdRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
  AdminProfessionalsIndexRoute: AdminProfessionalsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthEmailVerifiedRoute: typeof AuthEmailVerifiedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthEmailVerifiedRoute: AuthEmailVerifiedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillingRoute: typeof PatientBillingRoute
  PatientFindProfessionalRoute: typeof PatientFindProfessionalRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientMyProfessionalsRoute: typeof PatientMyProfessionalsRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientBookProfessionalIdRoute: typeof PatientBookProfessionalIdRoute
  PatientBookSuccessRoute: typeof PatientBookSuccessRoute
  PatientProfessionalProfessionalIdRoute: typeof PatientProfessionalProfessionalIdRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillingRoute: PatientBillingRoute,
  PatientFindProfessionalRoute: PatientFindProfessionalRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientMyProfessionalsRoute: PatientMyProfessionalsRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientBookProfessionalIdRoute: PatientBookProfessionalIdRoute,
  PatientBookSuccessRoute: PatientBookSuccessRoute,
  PatientProfessionalProfessionalIdRoute:
    PatientProfessionalProfessionalIdRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

interface ProfessionalRouteRouteChildren {
  ProfessionalAppointmentsRoute: typeof ProfessionalAppointmentsRoute
  ProfessionalInvoicesRoute: typeof ProfessionalInvoicesRoute
  ProfessionalMessagesRoute: typeof ProfessionalMessagesRoute
  ProfessionalMyPatientsRoute: typeof ProfessionalMyPatientsRoute
  ProfessionalNotificationsRoute: typeof ProfessionalNotificationsRoute
  ProfessionalPaymentRoute: typeof ProfessionalPaymentRoute
  ProfessionalProfileRoute: typeof ProfessionalProfileRoute
  ProfessionalScheduleTimingsRoute: typeof ProfessionalScheduleTimingsRoute
  ProfessionalSettingsRoute: typeof ProfessionalSettingsRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
  ProfessionalPatientPatientIdRoute: typeof ProfessionalPatientPatientIdRoute
}

const ProfessionalRouteRouteChildren: ProfessionalRouteRouteChildren = {
  ProfessionalAppointmentsRoute: ProfessionalAppointmentsRoute,
  ProfessionalInvoicesRoute: ProfessionalInvoicesRoute,
  ProfessionalMessagesRoute: ProfessionalMessagesRoute,
  ProfessionalMyPatientsRoute: ProfessionalMyPatientsRoute,
  ProfessionalNotificationsRoute: ProfessionalNotificationsRoute,
  ProfessionalPaymentRoute: ProfessionalPaymentRoute,
  ProfessionalProfileRoute: ProfessionalProfileRoute,
  ProfessionalScheduleTimingsRoute: ProfessionalScheduleTimingsRoute,
  ProfessionalSettingsRoute: ProfessionalSettingsRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
  ProfessionalPatientPatientIdRoute: ProfessionalPatientPatientIdRoute,
}

const ProfessionalRouteRouteWithChildren =
  ProfessionalRouteRoute._addFileChildren(ProfessionalRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  ProfessionalRouteRoute: ProfessionalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
