/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessionalRouteRouteImport } from './routes/professional/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalIndexRouteImport } from './routes/professional/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ProfessionalAppointmentsRouteImport } from './routes/professional/appointments'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerifiedRouteImport } from './routes/auth/email-verified'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'

const ProfessionalRouteRoute = ProfessionalRouteRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProfessionalAppointmentsRoute =
  ProfessionalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ProfessionalRouteRoute,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerifiedRoute = AuthEmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/professional': typeof ProfessionalRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/auth/': typeof AuthIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/auth': typeof AuthIndexRoute
  '/professional': typeof ProfessionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/professional': typeof ProfessionalRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/email-verified': typeof AuthEmailVerifiedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/professional/appointments': typeof ProfessionalAppointmentsRoute
  '/auth/': typeof AuthIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/professional'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/professional/appointments'
    | '/auth/'
    | '/professional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/professional/appointments'
    | '/auth'
    | '/professional'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/professional'
    | '/auth/email-verification'
    | '/auth/email-verified'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/professional/appointments'
    | '/auth/'
    | '/professional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProfessionalRouteRoute: typeof ProfessionalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/professional/appointments': {
      id: '/professional/appointments'
      path: '/appointments'
      fullPath: '/professional/appointments'
      preLoaderRoute: typeof ProfessionalAppointmentsRouteImport
      parentRoute: typeof ProfessionalRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verified': {
      id: '/auth/email-verified'
      path: '/email-verified'
      fullPath: '/auth/email-verified'
      preLoaderRoute: typeof AuthEmailVerifiedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthEmailVerifiedRoute: typeof AuthEmailVerifiedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthEmailVerifiedRoute: AuthEmailVerifiedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProfessionalRouteRouteChildren {
  ProfessionalAppointmentsRoute: typeof ProfessionalAppointmentsRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
}

const ProfessionalRouteRouteChildren: ProfessionalRouteRouteChildren = {
  ProfessionalAppointmentsRoute: ProfessionalAppointmentsRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
}

const ProfessionalRouteRouteWithChildren =
  ProfessionalRouteRoute._addFileChildren(ProfessionalRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProfessionalRouteRoute: ProfessionalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
