export interface SelectItem {
  value: string;
  label: string;
}

export const COUNTRIES_EN: SelectItem[] = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosniaAndHerzegovina", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "bruneiDarussalam", label: "Brunei Darussalam" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkinaFaso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "capeVerde", label: "Cape Verde" },
  { value: "centralAfricanRepublic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "congo", label: "Congo" },
  { value: "costaRica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czechRepublic", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominicanRepublic", label: "Dominican Republic" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "elSalvador", label: "El Salvador" },
  { value: "estonia", label: "Estonia" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "italy", label: "Italy" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kuwait", label: "Kuwait" },
  { value: "lebanon", label: "Lebanon" },
  { value: "libya", label: "Libya" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "mexico", label: "Mexico" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "newZealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "norway", label: "Norway" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "panama", label: "Panama" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saudiArabia", label: "Saudi Arabia" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "singapore", label: "Singapore" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "southAfrica", label: "South Africa" },
  { value: "southKorea", label: "South Korea" },
  { value: "spain", label: "Spain" },
  { value: "sriLanka", label: "Sri Lanka" },
  { value: "sudan", label: "Sudan" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "thailand", label: "Thailand" },
  { value: "tunisia", label: "Tunisia" },
  { value: "turkey", label: "Turkey" },
  { value: "ukraine", label: "Ukraine" },
  { value: "unitedArabEmirates", label: "United Arab Emirates" },
  { value: "unitedKingdom", label: "United Kingdom" },
  { value: "unitedStates", label: "United States" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const COUNTRIES_FR: SelectItem[] = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albanie" },
  { value: "algeria", label: "Algérie" },
  { value: "andorra", label: "Andorre" },
  { value: "angola", label: "Angola" },
  { value: "argentina", label: "Argentine" },
  { value: "armenia", label: "Arménie" },
  { value: "australia", label: "Australie" },
  { value: "austria", label: "Autriche" },
  { value: "azerbaijan", label: "Azerbaïdjan" },
  { value: "bahrain", label: "Bahreïn" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "belarus", label: "Biélorussie" },
  { value: "belgium", label: "Belgique" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Bénin" },
  { value: "bhutan", label: "Bhoutan" },
  { value: "bolivia", label: "Bolivie" },
  { value: "bosniaAndHerzegovina", label: "Bosnie-Herzégovine" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brésil" },
  { value: "bruneiDarussalam", label: "Brunéi Darussalam" },
  { value: "bulgaria", label: "Bulgarie" },
  { value: "burkinaFaso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cambodia", label: "Cambodge" },
  { value: "cameroon", label: "Cameroun" },
  { value: "canada", label: "Canada" },
  { value: "capeVerde", label: "Cap-Vert" },
  { value: "centralAfricanRepublic", label: "République centrafricaine" },
  { value: "chad", label: "Tchad" },
  { value: "chile", label: "Chili" },
  { value: "china", label: "Chine" },
  { value: "colombia", label: "Colombie" },
  { value: "comoros", label: "Comores" },
  { value: "congo", label: "Congo" },
  { value: "costaRica", label: "Costa Rica" },
  { value: "croatia", label: "Croatie" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Chypre" },
  { value: "czechRepublic", label: "République tchèque" },
  { value: "denmark", label: "Danemark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominicanRepublic", label: "République dominicaine" },
  { value: "ecuador", label: "Équateur" },
  { value: "egypt", label: "Égypte" },
  { value: "elSalvador", label: "Salvador" },
  { value: "estonia", label: "Estonie" },
  { value: "ethiopia", label: "Éthiopie" },
  { value: "finland", label: "Finlande" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambie" },
  { value: "georgia", label: "Géorgie" },
  { value: "germany", label: "Allemagne" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Grèce" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinée" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haïti" },
  { value: "hungary", label: "Hongrie" },
  { value: "iceland", label: "Islande" },
  { value: "india", label: "Inde" },
  { value: "indonesia", label: "Indonésie" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Irak" },
  { value: "ireland", label: "Irlande" },
  { value: "italy", label: "Italie" },
  { value: "jamaica", label: "Jamaïque" },
  { value: "japan", label: "Japon" },
  { value: "jordan", label: "Jordanie" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kuwait", label: "Koweït" },
  { value: "lebanon", label: "Liban" },
  { value: "libya", label: "Libye" },
  { value: "lithuania", label: "Lituanie" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaisie" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malte" },
  { value: "mexico", label: "Mexique" },
  { value: "morocco", label: "Maroc" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibie" },
  { value: "nepal", label: "Népal" },
  { value: "netherlands", label: "Pays-Bas" },
  { value: "newZealand", label: "Nouvelle-Zélande" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigéria" },
  { value: "norway", label: "Norvège" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "panama", label: "Panama" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Pérou" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Pologne" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Roumanie" },
  { value: "russia", label: "Russie" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saudiArabia", label: "Arabie saoudite" },
  { value: "senegal", label: "Sénégal" },
  { value: "serbia", label: "Serbie" },
  { value: "singapore", label: "Singapour" },
  { value: "slovakia", label: "Slovaquie" },
  { value: "slovenia", label: "Slovénie" },
  { value: "southAfrica", label: "Afrique du Sud" },
  { value: "southKorea", label: "Corée du Sud" },
  { value: "spain", label: "Espagne" },
  { value: "sriLanka", label: "Sri Lanka" },
  { value: "sudan", label: "Soudan" },
  { value: "sweden", label: "Suède" },
  { value: "switzerland", label: "Suisse" },
  { value: "syria", label: "Syrie" },
  { value: "taiwan", label: "Taïwan" },
  { value: "tanzania", label: "Tanzanie" },
  { value: "thailand", label: "Thaïlande" },
  { value: "tunisia", label: "Tunisie" },
  { value: "turkey", label: "Turquie" },
  { value: "ukraine", label: "Ukraine" },
  { value: "unitedArabEmirates", label: "Émirats arabes unis" },
  { value: "unitedKingdom", label: "Royaume-Uni" },
  { value: "unitedStates", label: "États-Unis" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Ouzbékistan" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yémen" },
  { value: "zambia", label: "Zambie" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const getCountries = (lang: string) =>
  lang === "fr" ? COUNTRIES_FR : COUNTRIES_EN;

export const RELATIONSHIPS_EN: SelectItem[] = [
  { value: "parent", label: "Parent" },
  { value: "child", label: "Child" },
  { value: "spouse", label: "Spouse" },
  { value: "partner", label: "Partner" },
  { value: "sibling", label: "Sibling" },
  { value: "grandparent", label: "Grandparent" },
  { value: "grandchild", label: "Grandchild" },
  { value: "relative", label: "Relative" },
  { value: "friend", label: "Friend" },
  { value: "neighbor", label: "Neighbor" },
  { value: "caregiver", label: "Caregiver" },
  { value: "guardian", label: "Guardian" },
  { value: "doctor", label: "Doctor" },
  { value: "nurse", label: "Nurse" },
  { value: "colleague", label: "Colleague" },
  { value: "other", label: "Other" },
];

export const RELATIONSHIPS_FR: SelectItem[] = [
  { value: "parent", label: "Parent" },
  { value: "child", label: "Enfant" },
  { value: "spouse", label: "Époux/se" },
  { value: "partner", label: "Partenaire" },
  { value: "sibling", label: "Frère/Sœur" },
  { value: "grandparent", label: "Grand-parent" },
  { value: "grandchild", label: "Petit-enfant" },
  { value: "relative", label: "Parent" },
  { value: "friend", label: "Ami" },
  { value: "neighbor", label: "Voisin" },
  { value: "caregiver", label: "Aidant" },
  { value: "guardian", label: "Tuteur" },
  { value: "doctor", label: "Médecin" },
  { value: "nurse", label: "Infirmier/ère" },
  { value: "colleague", label: "Collègue" },
  { value: "other", label: "Autre" },
];

export const getRelationships = (lang: string) =>
  lang === "fr" ? RELATIONSHIPS_FR : RELATIONSHIPS_EN;

export const SPECIALIZATIONS_EN: SelectItem[] = [
  { value: "generalPractitioner", label: "General Practitioner" },
  { value: "familyMedicine", label: "Family Medicine" },
  { value: "internalMedicine", label: "Internal Medicine" },
  { value: "generalSurgery", label: "General Surgery" },
  { value: "orthopedicSurgery", label: "Orthopedic Surgery" },
  { value: "neurosurgery", label: "Neurosurgery" },
  { value: "plasticSurgery", label: "Plastic Surgery" },
  { value: "cardiothoracicSurgery", label: "Cardiothoracic Surgery" },
  { value: "urology", label: "Urology" },
  { value: "radiology", label: "Radiology" },
  { value: "pathology", label: "Pathology" },
  { value: "emergencyMedicine", label: "Emergency Medicine" },
  { value: "criticalCare", label: "Critical Care" },
  { value: "obstetricsAndGynecology", label: "Obstetrics and Gynecology" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "psychology", label: "Psychology" },
  { value: "cardiology", label: "Cardiology" },
  { value: "pulmonology", label: "Pulmonology" },
  { value: "gastroenterology", label: "Gastroenterology" },
  { value: "nephrology", label: "Nephrology" },
  { value: "endocrinology", label: "Endocrinologie" },
  { value: "dermatology", label: "Dermatology" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "ent", label: "ENT" },
  { value: "dentistry", label: "Dentistry" },
  { value: "physiotherapy", label: "Physiotherapy" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "nursing", label: "Nursing" },
  { value: "other", label: "Other" },
];

export const SPECIALIZATIONS_FR: SelectItem[] = [
  { value: "generalPractitioner", label: "Médecin Généraliste" },
  { value: "familyMedicine", label: "Médecine Familiale" },
  { value: "internalMedicine", label: "Médecine Interne" },
  { value: "generalSurgery", label: "Chirurgie Générale" },
  { value: "orthopedicSurgery", label: "Chirurgie Orthopédique" },
  { value: "neurosurgery", label: "Neurochirurgie" },
  { value: "plasticSurgery", label: "Chirurgie Plastique" },
  { value: "cardiothoracicSurgery", label: "Chirurgie Cardiothoracique" },
  { value: "urology", label: "Urologie" },
  { value: "radiology", label: "Radiologie" },
  { value: "pathology", label: "Pathologie" },
  { value: "emergencyMedicine", label: "Médecine d'Urgence" },
  { value: "criticalCare", label: "Soins Intensifs" },
  { value: "obstetricsAndGynecology", label: "Obstétrique et Gynécologie" },
  { value: "pediatrics", label: "Pédiatrie" },
  { value: "psychiatry", label: "Psychiatrie" },
  { value: "psychology", label: "Psychologie" },
  { value: "cardiology", label: "Cardiologie" },
  { value: "pulmonology", label: "Pneumologie" },
  { value: "gastroenterology", label: "Gastro-entérologie" },
  { value: "nephrology", label: "Néphrologie" },
  { value: "endocrinology", label: "Endocrinologie" },
  { value: "dermatology", label: "Dermatologie" },
  { value: "ophthalmology", label: "Ophtalmologie" },
  { value: "ent", label: "ORL" },
  { value: "dentistry", label: "Dentisterie" },
  { value: "physiotherapy", label: "Physiothérapie" },
  { value: "pharmacy", label: "Pharmacie" },
  { value: "nursing", label: "Soins Infirmiers" },
  { value: "other", label: "Autre" },
];

export const getSpecializations = (lang: string) =>
  lang === "fr" ? SPECIALIZATIONS_FR : SPECIALIZATIONS_EN;
