export interface SelectItem {
  value: string;
  label: string;
}

export const COUNTRIES: SelectItem[] = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosniaAndHerzegovina", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "bruneiDarussalam", label: "Brunei Darussalam" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkinaFaso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "capeVerde", label: "Cape Verde" },
  { value: "centralAfricanRepublic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "congo", label: "Congo" },
  { value: "costaRica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czechRepublic", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominicanRepublic", label: "Dominican Republic" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "elSalvador", label: "El Salvador" },
  { value: "estonia", label: "Estonia" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "israel", label: "Israel" },
  { value: "italy", label: "Italy" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kuwait", label: "Kuwait" },
  { value: "lebanon", label: "Lebanon" },
  { value: "libya", label: "Libya" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "mexico", label: "Mexico" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "newZealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "norway", label: "Norway" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "panama", label: "Panama" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saudiArabia", label: "Saudi Arabia" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "singapore", label: "Singapore" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "southAfrica", label: "South Africa" },
  { value: "southKorea", label: "South Korea" },
  { value: "spain", label: "Spain" },
  { value: "sriLanka", label: "Sri Lanka" },
  { value: "sudan", label: "Sudan" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "thailand", label: "Thailand" },
  { value: "tunisia", label: "Tunisia" },
  { value: "turkey", label: "Turkey" },
  { value: "ukraine", label: "Ukraine" },
  { value: "unitedArabEmirates", label: "United Arab Emirates" },
  { value: "unitedKingdom", label: "United Kingdom" },
  { value: "unitedStates", label: "United States" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const RELATIONSHIPS: SelectItem[] = [
  { label: "Parent", value: "parent" },
  { label: "Child", value: "child" },
  { label: "Spouse", value: "spouse" },
  { label: "Partner", value: "partner" },
  { label: "Sibling", value: "sibling" },
  { label: "Grandparent", value: "grandparent" },
  { label: "Grandchild", value: "grandchild" },
  { label: "Relative", value: "relative" },
  { label: "Friend", value: "friend" },
  { label: "Neighbor", value: "neighbor" },
  { label: "Caregiver", value: "caregiver" },
  { label: "Guardian", value: "guardian" },
  { label: "Doctor", value: "doctor" },
  { label: "Nurse", value: "nurse" },
  { label: "Colleague", value: "colleague" },
  { label: "Other", value: "other" },
];

export const SPECIALIZATIONS: SelectItem[] = [
  { label: "General Practitioner", value: "generalPractitioner" },
  { label: "Family Medicine", value: "familyMedicine" },
  { label: "Internal Medicine", value: "internalMedicine" },
  { label: "General Surgery", value: "generalSurgery" },
  { label: "Orthopedic Surgery", value: "orthopedicSurgery" },
  { label: "Neurosurgery", value: "neurosurgery" },
  { label: "Plastic Surgery", value: "plasticSurgery" },
  { label: "Cardiothoracic Surgery", value: "cardiothoracicSurgery" },
  { label: "Urology", value: "urology" },
  { label: "Radiology", value: "radiology" },
  { label: "Pathology", value: "pathology" },
  { label: "Emergency Medicine", value: "emergencyMedicine" },
  { label: "Critical Care", value: "criticalCare" },
  { label: "Obstetrics and Gynecology", value: "obstetricsAndGynecology" },
  { label: "Pediatrics", value: "pediatrics" },
  { label: "Psychiatry", value: "psychiatry" },
  { label: "Psychology", value: "psychology" },
  { label: "Cardiology", value: "cardiology" },
  { label: "Pulmonology", value: "pulmonology" },
  { label: "Gastroenterology", value: "gastroenterology" },
  { label: "Nephrology", value: "nephrology" },
  { label: "Endocrinology", value: "endocrinology" },
  { label: "Dermatology", value: "dermatology" },
  { label: "Ophthalmology", value: "ophthalmology" },
  { label: "ENT", value: "ent" },
  { label: "Dentistry", value: "dentistry" },
  { label: "Physiotherapy", value: "physiotherapy" },
  { label: "Pharmacy", value: "pharmacy" },
  { label: "Nursing", value: "nursing" },
  { label: "Other", value: "other" },
];
